apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: test-robotics
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: test
    - name: prod

  components:
    - name: turtlebot-simulator
      resources:
        requests:
          memory: "8Gi"
          cpu: "1000m"
        limits:
          memory: "8Gi"
          cpu: "1000m"
      image: ghcr.io/aestene/isar-turtlebot:latest
      ports:
        - name: ros
          port: 9090
        - name: videostream
          port: 5000
      publicPort: videostream
      ingressConfiguration:
        - websocketfriendly
      variables:
        TELEOP_CONTROLLER: disabled
        ENABLE_MANIPULATOR: false
        MANIPULATOR_GUI: disabled
        HEADLESS: true
        GAZEBO_MASTER_URI: turtlebot-simulator:11345
